Module6 task2
htmlacademy-php/1168091-readme-12 pull request #11
Opened 2021-01-27 18:50 UTC by kandrukKV

2021-02-01 10:17 UTC, CforCAT requested changes

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +if (isset($_POST['submit'])) {
Я бы чекал $_SERVER['REQUEST_METHOD']

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +        $errors[$current_tab . '-title'] = 'Заголовок. Это поле должно быть заполнено.';
А для чего ты называл поля $current_tab . '-title' и подобные? Это не критично, просто мне интересно вкладывал ли ты в это какой-то смысл

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +                } elseif ($file_size > 2000000) {
Я чет не нашел в ТЗ ограничение на 2MB

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +                $add_result = add_quote_post($con, $_POST['quote-title'], $_POST['quote-content'], $_POST['quote-author'], $current_tab, 3);
Почему бы не делать это в одной функции? В параметры функции передавать null вместо quote-author. В MySQL тоже можно инсертить null. И тогда будет одна универсальная функция для добавления поста

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +        if ($add_result) {
Ты кажется пропустил привязку постов к тегам

2021-02-01 10:17 UTC, CforCAT commented on functions.php
> +        if (!preg_match("/(^|\B)#(?![0-9_]+\b)([a-zA-Z0-9_]{1,19})(\b|\r)/", $tags[$i])) {
Где взял регулярку? :-)
По ТЗ тут должны быть слова разделенные пробелом без #. И определенно слова должны быть на русском языке в том числе

2021-02-01 10:17 UTC, CforCAT commented on templates/layout.php
> +                                <a class="header__post-button header__post-button--active button button--transparent" href="#">Закрыть</a>
Ссылку бы рабочую поставить

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +            header('Location:' . 'post.php?id=' . mysqli_insert_id($con));
Вот здесь сценарий нужно завершать

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +        echo $current_tab;
Я так понимаю это для отладки?

2021-02-01 10:17 UTC, CforCAT commented on functions.php
> +    vardump($content_type_id);
Для отладки? В функции ниже тоже есть

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +                if ($file_is_saved) {
Если при сохранении файла будет ошибка (например нет прав на запись в директории), то пост не сохранится и не выведется никаких ошибок

2021-02-01 10:17 UTC, CforCAT commented on add.php
> +        if ($add_result) {
И на странице поста их надо будет выводить

2021-02-02 20:31 UTC, kandrukKV commented on add.php
> +        $errors[$current_tab . '-title'] = 'Заголовок. Это поле должно быть заполнено.';
Я таким образом пытался сделать привязку конкретных ошибок к конкретному табу. Чтобы все подряд ошибки не писались во все табы сразу. Не понятно что лучше? Может конечно было бы проще в каждом табе прописать там где вывод ошибки, что если например $current_tab === 'text', то выводить ошибки для него. Ну вот смысл был примерно таким.))

2021-02-02 20:34 UTC, kandrukKV commented on add.php
> +            header('Location:' . 'post.php?id=' . mysqli_insert_id($con));
Поясни пожалуйста что значит завершать сценарий? Это должно быть последней строчкой скрипта?

2021-02-02 21:56 UTC, CforCAT commented on add.php
> +            header('Location:' . 'post.php?id=' . mysqli_insert_id($con));
После header с Location надо написать exit()

2021-02-02 21:57 UTC, CforCAT commented on add.php
> +        $errors[$current_tab . '-title'] = 'Заголовок. Это поле должно быть заполнено.';
У тебя всегда есть параметр, чтобы чекать текущий таб. Там же и ошибки выводить, на текущем табе

2021-02-07 08:10 UTC, merged